## Implementing Keras Libraray on breast cancer detection

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense

In [ ]:
data=load_breast_cancer()

data.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer diagnostic (Meha Desai , Manan Shah ,
1- Department of Electronics and Instrumentation Engineering, School of Electronics and Electrical Engineering, Vellore Institute of Technology, Tamil Nadu, India
2- Department of Chemical Engineering, School of Technology, Pandit Deendayal Petroleum University, Gandhinagar, Gujarat, India) Dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radius, field
        10 is Radius SE, field 20 is Worst Radius.

        - class:
                - Malignant
                - Benign

    :Summary Statistics:

    ===================================== ====== ======
                                           Min    Max
    ===================================== ====== ======
    radius (mean):                        6.981  28.11
    texture (mean):                       9.71   39.28
    perimeter (mean):                     43.79  188.5
    area (mean):                          143.5  2501.0
    smoothness (mean):                    0.053  0.163
    compactness (mean):                   0.019  0.345
    concavity (mean):                     0.0    0.427
    concave points (mean):                0.0    0.201
    symmetry (mean):                      0.106  0.304
    fractal dimension (mean):             0.05   0.097
    radius (standard error):              0.112  2.873
    texture (standard error):             0.36   4.885
    perimeter (standard error):           0.757  21.98
    area (standard error):                6.802  542.2
    smoothness (standard error):          0.002  0.031
    compactness (standard error):         0.002  0.135
    concavity (standard error):           0.0    0.396
    concave points (standard error):      0.0    0.053
    symmetry (standard error):            0.008  0.079
    fractal dimension (standard error):   0.001  0.03
    radius (worst):                       7.93   36.04
    texture (worst):                      12.02  49.54
    perimeter (worst):                    50.41  251.2
    area (worst):                         185.2  4254.0
    smoothness (worst):                   0.071  0.223
    compactness (worst):                  0.027  1.058
    concavity (worst):                    0.0    1.252
    concave points (worst):               0.0    0.291
    symmetry (worst):                     0.156  0.664
    fractal dimension (worst):            0.055  0.208
    ===================================== ====== ======

    :Missing Attribute Values: None

    :Class Distribution: 212 - Malignant, 357 - Benign

    :Creator:  Meha Desai , Manan Shah , Indian Professors

    :Donor: Clinical eHealth

    :Date: October, 2022


In [ ]:
data['data'].shape

(569, 30)

In [ ]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [ ]:
j=0
for i in data['feature_names']:
  print(i,':',data['data'][0][j])
  j+=1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189

In [ ]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
feature=data['data']
label=data['target']
feature.shape

(569, 30)

In [ ]:
scale= StandardScaler()

feature= scale.fit_transform(feature)
     
j=0
for i in data['feature_names']:
  print(i,':',feature[0][j])
  j+=1

  print(feature[0])
print(data['target_names'][label[0]])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
malignant

In [ ]:
df_frt=pd.DataFrame(feature, columns= data['feature_names'])
df_lbl=pd.DataFrame(label, columns= ['label'])
df=pd.concat([df_frt,df_lbl], axis=1)
df= df.sample(frac=1)
df

In [ ]:
	mean_radius	 mean_texture	mean_perimeter	mean_area	mean_smoothness	    mean_compactness	mean_concavity	mean_concave_points	 mean_symmetry	mean_fractal_dimension	...	 worst_texture	worst_perimeter	 worst_area	 worst_smoothness	worst_compactness	worst_concavity	 worst_concave_points	worst_symmetry	worst_fractal_dimension	  label
459	 -1.241793	  2.073499	      -1.247611	   -1.035222	-1.175673	       -1.100721	      -0.921401	        -0.992788	      -0.695938	         -0.464635	        ...	  1.830816	      -1.168535	     -0.932895	   -0.936711	       -0.912002	      -0.960889	          -1.004137	            -0.937918	       -0.655891	        1
253	  0.901094	 -0.514200	       0.866270	    0.777324	 0.315955	       -0.004567	       0.474586	         0.892752	       0.005043	         -0.945203	        ...	 -0.095626	       0.704101	      0.600181	    0.404667	       -0.087565	       0.314773	           1.082516	             0.383809	       -0.156041	        0
351	  0.460872       -0.016208	       0.623248	    0.294964	 1.988342	        2.502714	       2.543646	         1.941793	       2.056873	          1.875829	        ...	 -0.245442	       0.361564	      0.061029	    0.992068	        1.592480	       1.991028	           1.505816	             2.174692	        1.166735	        0
45	  1.284513	 -0.393193	       1.307005	    1.197683	 0.963560	        1.217803	       1.363478	         1.340793	       0.348232	         -0.327128	        ...	 -0.709547	       1.290882	      1.206661	    1.557551	        1.620470	       2.217950	           1.875822	             1.453162	        0.438017	        0
250	  1.934906	  0.993739	       1.933096	    2.016784	 0.308838	        1.066192	       2.290035	         2.117192	       1.436213	         -0.541186	        ...	  0.215406	       1.728734	      1.985416	   -0.493969	        0.400354	       2.048118	           1.460136	             0.364396	       -0.302339	        0
...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...	...
112	  0.037691	  0.083856	       0.241414	   -0.071072	-1.280286	        2.254449	       2.655385	         0.749595	      -0.392910	          2.111151	        ...	 -0.317093	      -0.007780	     -0.301628	   -1.879621	        1.049853	       1.948330	           0.546540	            -0.813348	        1.344065	        1
476	  0.020650	  0.288638	       0.018164	   -0.103779	-0.501736	        0.122408	      -0.479215	        -0.473040	      -1.115796	         -0.383832	        ...	  0.257745	       0.144127	     -0.091558	   -0.748217	        0.563842	      -0.100693	           0.293779	            -0.593330	       -0.297351	        1
548	 -1.262242	  0.011717	      -1.273561	   -1.050012	-0.814864	       -1.024157	      -0.821463	        -1.013810	      -0.845627	         -0.063453	        ...	 -0.014204	      -1.136664	     -0.907756	   -0.546572	       -1.010222	      -0.857262	          -1.159448	            -0.564210	       -0.262993	        1
219	  1.534446	  3.067156	       1.484123	    1.615766	-0.865392	        0.164101	       0.322671	         0.450127	      -1.400570	         -1.370484	        ...	  3.213360	       2.172543	      2.806362	    0.369598	        0.988783	       0.610780	           0.729259	            -0.303748	       -0.458057	        0
487	  1.508885	 -0.109290	       1.488242	    1.456496	 0.892395	        0.766758	       1.717529	         1.817982	       0.041553	         -0.233566	        ...	  0.767446	       1.389175	      1.510780	    0.834259	        0.752140	       1.541979	           1.391616	             0.590885	        0.340485	        0	

569 rows × 31 columns

In [ ]:

#500 Training
x_train = feature[:500]
y_train = label[:500]

#35 Validation
x_val = feature[500:535]
y_val = label[500:535]

#34 Testing
x_test = feature[535:]
y_test = label[535:]

x_train.shape

(500, 30)

In [ ]:
from keras.backend import binary_crossentropy
model=Sequential()
model.add(Dense(64, activation='relu', input_dim= 30))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'] )

In [ ]:
model.fit(x_train, y_train, batch_size=1, epochs=10, validation_data=(x_val, y_val))

Epoch 1/10
500/500 [==============================] - 2s 2ms/step - loss: 0.1791 - accuracy: 0.9400 - val_loss: 0.0409 - val_accuracy: 1.0000
Epoch 2/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0839 - accuracy: 0.9720 - val_loss: 0.0524 - val_accuracy: 0.9714
Epoch 3/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0480 - accuracy: 0.9840 - val_loss: 0.0923 - val_accuracy: 0.9714
Epoch 4/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0340 - accuracy: 0.9860 - val_loss: 0.1458 - val_accuracy: 0.9714
Epoch 5/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0289 - accuracy: 0.9920 - val_loss: 0.1386 - val_accuracy: 0.9714
Epoch 6/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0266 - accuracy: 0.9940 - val_loss: 0.1875 - val_accuracy: 0.9714
Epoch 7/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0251 - accuracy: 0.9920 - val_loss: 0.1633 - val_accuracy: 0.9714
Epoch 8/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0214 - accuracy: 0.9940 - val_loss: 0.1447 - val_accuracy: 0.9714
Epoch 9/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0211 - accuracy: 0.9940 - val_loss: 0.1161 - val_accuracy: 0.9714
Epoch 10/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0092 - accuracy: 0.9960 - val_loss: 0.1241 - val_accuracy: 0.9714
<keras.callbacks.History at 0x7fcb16f48150>

In [ ]:
x_train[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [ ]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.0105 - accuracy: 1.0000
[0.01050428207963705, 1.0]

In [ ]:
y_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
y_val

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [ ]:

sample= x_test[10]

sample.shape

(30,)

In [ ]:
sample

array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])

In [ ]:
for i in range(30):
  sample=x_test[i]
  sample=np.reshape(sample,(1,30))

  if model.predict(sample)[0][0] >0.5 :
    print("-Benign")
  else:
    print("-Malignant")

  if y_test[i]==1:
    print("*Benign")
  else:
    print("*Malignant")  

  print("------")  

-Malignant
*Malignant
------
-Malignant
*Malignant
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Malignant
*Malignant
------
-Malignant
*Malignant
------
-Malignant
*Malignant
------

In [ ]:
sample.shape

(1, 30)

In [ ]:
model.predict(sample)

array([[4.8561056e-18]], dtype=float32)

In [ ]:
x_test[0]

array([ 1.82414032,  0.36543133,  1.88778669,  1.85751441,  0.58638323,
        1.31824626,  1.50283863,  2.14814488,  1.15143953, -0.04077169,
        1.05904307, -0.4114087 ,  0.910827  ,  1.04382537, -0.82102626,
        0.03810891,  0.27043808,  0.3915519 , -0.12862155, -0.41830962,
        1.66304049, -0.03211657,  1.57682617,  1.63207582, -0.24410428,
        0.37681708,  0.82091153,  1.5256103 ,  0.28512459, -0.45750286])

In [ ]:

y_test[0]

0

In [ ]:
x_test[10]

array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])

In [ ]:
y_test[10]

1